### ISSUE TITLE
The detail information of reconstruction map is fuzzy

### ISSUE THREAD

**Issue by mozhuqing** [AdneneBoumessouer/MVTec-Anomaly-Detection#15]
Hello, I have a question. Why is the reconstructed image missing the details? For example, hazelnut, whose reconstruction details are fuzzy. The details of the pictures you have made are also some true. The words "500" on the capsule are very vague.

**Comment by AdneneBoumessouer** [comment]
One limitation of the Auto-Encoder is the unability to reconstruct some details that are present only in a very small subset of the total training image dataset, like the 500 observed in some pill-images. I have considerably improved the code. Try working with the new version.
